#!/usr/bin/env bash

STORAGE=$PW_PATH/pw.txt
touch -- "$STORAGE"

COL_SP=':::::'

help () {
	echo -e "Утилита для копирования значения по ключу из файла в буфер\n"
	echo -e "Доступные параметры:\n"
	echo "pw -add <key> <value> - добавление пары ключ/значение"
	echo "pw -rm <key>          - удаление записи по ключу"
	echo "pw -ls                - получение всех ключей из файла"
	echo "pw <key>              - копирование значения по ключу"
	echo "pw -ssh <key>         - копирование значения, запуск ssh"
	exit
}

err () {
	echo $1
	exit
}

invalid () {
	err "Команда $1 не существует"
}

add () {
	if [[ -z $2 ]] ; then
		err "Введите ключ"
	fi

	if grep -q '^'$2 $STORAGE ; then
		err "Ключ $2 уже существует"
	fi

	if [[ -z $3 ]] ; then
		err "Введите значение"
	fi

	if [[ -z $4 ]] ; then
		PASSWORD=$3
		ENCRYPT=0
	else
		PASSWORD=$(echo $3 | openssl aes-256-cbc -a -A)
		ENCRYPT=1
	fi

	LOGIN=$2

	printf "%s${COL_SP}%s${COL_SP}%s\n" $LOGIN $PASSWORD $ENCRYPT >> $STORAGE
}

remove () {
	sed -E "/^$2$COL_SP.*$/d" $STORAGE > $STORAGE.bak && mv $STORAGE.bak $STORAGE
}

list () {
	cat $STORAGE | awk -F $COL_SP '{print $1}'
}

get () {
	if [ -z "$1" ] ; then
		err "Введите ключ или команду"
	fi

	if [ -z $1 ] ; then
		err "Введите ключ"
	fi

	PASSWORD=$(awk -F $COL_SP '/^'$1$COL_SP'/{print $2}' $STORAGE)

	if [ -z $PASSWORD ] ; then
		err "Ключ $1 не существует"
	fi

	if [[ $(awk -F $COL_SP '/^'$1'/{print $3}' $STORAGE) -eq 1 ]] ; then
		PASSWORD=$(echo $PASSWORD | openssl aes-256-cbc -a -A -d)
	fi

	copy $PASSWORD
}

copy () {
	if [ "$(uname)" == "Darwin" ]; then
		echo $1 | tr -d '\n' | pbcopy    
	elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
		echo $1 | tr -d '\n' | xclip -selection c
	# elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
	    # Do something under 32 bits Windows NT platform
	# elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
	    # Do something under 64 bits Windows NT platform
	fi
}

cssh () {
	get $2
	ssh $2
}

case $1 in
	-help) help ;;

	-add)  add $@ ;;
	-rm)   remove $@ ;;

	-ls)   list ;;

	-ssh)  cssh $@ ;;

	-*)    invalid $@ ;;
	*)     get $1 ;;
esac