#!/bin/bash

STORAGE=$PW_PATH/pw.txt
touch -- "$STORAGE"

COL_SP=':::::'

help () {
	echo -e "Утилита для быстрого копирования значения по ключу из файла в буфер\nДоступные параметры:"
	echo -e "\t- list              - получение всех строк из файла"
	echo -e "\t- get <key>         - копирование значения по указанному ключу в буфер"
	echo -e "\t- add <key> <value> - добавление новой пары ключ/значение"
	echo -e "\t- delete <key>      - удаление записи по ключу"
	exit
}

if [ -z "$1" ] ; then
	help
fi

err () {
	echo $1
	exit
}

invalid () {
	err "Команда $1 не существует"
}

list () {
	cat $STORAGE | awk -F $COL_SP '{print $1}'
}

get () {
	PASSWORD=$(awk -F $COL_SP '/^'$1$COL_SP'/{print $2}' $STORAGE)

	if [ -z $1 ] ; then
		err "Введите ключ"
	fi

	if [ -z $PASSWORD ] ; then
		err "Ключ $1 не существует"
	fi

	if [[ $(awk -F $COL_SP '/^'$1'/{print $3}' $STORAGE) -eq 1 ]] ; then
		PASSWORD=$(echo $PASSWORD | openssl aes-256-cbc -a -A -d)
	fi

	echo $PASSWORD | tr -d '\n' | pbcopy
}

remove () {
	sed -E "/^$2$COL_SP.*$/d" $STORAGE > $STORAGE.bak && mv $STORAGE.bak $STORAGE
}

add () {
	if grep -q '^'$2 $STORAGE ; then
		err "Такой ключ уже существует"
	fi

	if [[ -z $2 || -z $3 ]] ; then
		err " Введите ключ и значение"
	fi

	LOGIN=$2

	if [[ -z $4 ]] ; then
		PASSWORD=$3
		ENCRYPT=0
	else
		PASSWORD=$(echo $3 | openssl aes-256-cbc -a -A)
		ENCRYPT=1
	fi

	printf "%s${COL_SP}%s${COL_SP}%s\n" $LOGIN $PASSWORD $ENCRYPT >> $STORAGE
}

cssh () {
	get $2
	ssh $2
}

case $1 in
	-help) help ;;
	-ls) list ;;

	-add)  add $@ ;;
	-rm)  remove $@ ;;

	-ssh)  cssh $@ ;;

	-*)  invalid $@ ;;
	*)  get $1 ;;
esac